CREATE TABLE account
(
    ID      BIGINT IDENTITY NOT NULL PRIMARY KEY,
    NAME    VARCHAR(100)    NOT NULL,
    BALANCE DECIMAL(16, 2)  NOT NULL
);

CREATE TABLE transaction
(
    ID     BIGINT IDENTITY NOT NULL PRIMARY KEY,
    DEBIT  BIGINT          NOT NULL,
    CREDIT BIGINT          NOT NULL,
    AMOUNT DECIMAL(16, 2)  NOT NULL,
    STATUS VARCHAR(100)    NOT NULL,
    FOREIGN KEY (DEBIT) REFERENCES account (ID),
    FOREIGN KEY (CREDIT) REFERENCES account (ID)
);

INSERT INTO ACCOUNT (NAME, BALANCE)
VALUES ('Bill Gates', 1000000.00);
INSERT INTO ACCOUNT (NAME, BALANCE)
VALUES ('Elon Musk', 200000.00);



INSERT INTO transaction (ID, DEBIT, CREDIT, AMOUNT, STATUS)
VALUES (1, 1, 2, 100.00, 'SUCCESSFUL');